import type { Metadata } from "next";
import { Kantumruy_Pro } from "next/font/google";
import "@/app/_styles/globals.css";
import { Header, TanstackProvider } from "./_components";

const kantumruyPro = Kantumruy_Pro({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${kantumruyPro.className}`}>
        <TanstackProvider>
          <Header />
          <main id="app">{children}</main>
        </TanstackProvider>
      </body>
    </html>
  );
}
